Fastly assets: cache Set-Cookie responses
So that we pass this CDN test:

    === RUN TestCacheHeaderSetCookie
    --- FAIL: TestCacheHeaderSetCookie (0.12 seconds)
      helpers.go:378: Request 2 received incorrect response body. Expected "first response", got "subsequent response"
      helpers.go:378: Request 3 received incorrect response body. Expected "first response", got "subsequent response"
      helpers.go:387: Origin received the wrong number of requests. Expected 1, got 3