Fastly assets: don't cache no-(store|cache) resps
So that we pass these tests:

    === RUN TestNoCacheCacheControlNoCache
    --- FAIL: TestNoCacheCacheControlNoCache (0.05 seconds)
      helpers.go:428: Request 2 received incorrect response body. Expected "second response", got "first response"
      helpers.go:428: Request 3 received incorrect response body. Expected "third response", got "first response"
    === RUN TestNoCacheCacheControlNoStore
    --- FAIL: TestNoCacheCacheControlNoStore (0.06 seconds)
      helpers.go:428: Request 2 received incorrect response body. Expected "second response", got "first response"
      helpers.go:428: Request 3 received incorrect response body. Expected "third response", got "first response"