Fastly assets: remove custom req.http.host
The origin for assets responds to both `assets.digital` and
`assets-origin.production` so we don't need to munge the Host header on the
original request.

    ➜  ~  curlh -H "Host: assets.digital.cabinet-office.gov.uk" https://assets-origin.production.alphagov.co.uk/__canary__\?$(date +%s)
    HTTP/1.1 200 OK
    Server: nginx
    Date: Fri, 14 Nov 2014 15:58:20 GMT
    Content-Type: application/json
    Content-Length: 27
    Connection: close
    Cache-Control: max-age=0, no-store, no-cache
    Strict-Transport-Security: max-age=31536000

This allows it to pass the CDN tests:

    === RUN TestReqHeaderHostUnmodified
    --- FAIL: TestReqHeaderHostUnmodified (0.02 seconds)
      cdn_req_headers_test.go:140: Origin received "Host" header with modified value. Expected "fastly.cdn-acceptance-test.alphagov.co.uk", got "assets-origin.production.alphagov.co.uk"