Fastly assets: prevent PURGE requests
To make this CDN test pass:

    === RUN TestMiscRestrictPurgeRequests
    --- FAIL: TestMiscRestrictPurgeRequests (0.07 seconds)
      cdn_misc_test.go:105: Request 2 received incorrect status code. Expected 403, got 200
      cdn_misc_test.go:87: Request should not have made it to origin
      cdn_misc_test.go:120: Request 3 received incorrect response body. Expected "this should not be purged", got "origin"

I'm not adding any addresses to a whitelist ACL because we haven't, to date,
needed to purge from this service.